version: "3.7"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /home/cap_ironbump/volumes
    ports:
      - 3306:3306